# Numpy
***
## 常用概念
***

### 对象的副本或视图

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
b=a

In [4]:
b

array([1, 2, 3, 4])

In [5]:
a[2]=0

In [6]:
b

array([1, 2, 0, 4])

In [7]:
c = a[0:2]

In [8]:
c

array([1, 2])

In [9]:
a[0] = 0

In [10]:
c

array([0, 2])

In [12]:
a = np.array([1,2,3,4])

In [13]:
c = a.copy()

In [14]:
c

array([1, 2, 3, 4])

In [15]:
a[2]=0

In [16]:
c

array([1, 2, 3, 4])

***
## 向量化
***

***
## 广播机制
***

In [17]:
A = np.arange(16).reshape(4,4)

In [18]:
b = np.arange(4)

In [19]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
b

array([0, 1, 2, 3])

    size a 4*4
    size b 4
***兼容性规则：如果两个数组每一维等长，或者其中一个数组为1维。满足兼容性，广播机制适用***    
**规则1:广播机制会将丢失的一个维度视为1**   
    size a 4x4   
    size b 4x1   
**规则2:假定缺失元素（一维）都用已有值进行填充**   
参：P50

In [24]:
A+b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

    结果展示为每一列都加上了b

In [26]:
m = np.arange(6).reshape(3,1,2)

In [27]:
m

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [28]:
n = np.arange(6).reshape(3,2,1)

In [29]:
n

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

In [32]:
n[2,1,0]

5

In [34]:
m+n

array([[[ 0,  1],
        [ 1,  2]],

       [[ 4,  5],
        [ 5,  6]],

       [[ 8,  9],
        [ 9, 10]]])

***
## 结构化数组
即同样是用np存储的数组，只不过可以存放任意的数据类型在同一个list之中。要在最后适用dtype声明之前个中数据的类型；   
类似与数据库声明
***

In [35]:
structured = np.array([(1,'first',0.5,1+2j),(2,'second',1.3,2-2j),(3,'third',0.8,1+3j)],dtype=('i2,a6,f4,c8'))

In [36]:
structured

array([(1, b'first', 0.5, 1.+2.j), (2, b'second', 1.3, 2.-2.j),
       (3, b'third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [37]:
structured = np.array([(1,'first',0.5,1.+2.j),(2,'second',1.3,2.-2.j),(3,'third',0.8,1.+3.j)],dtype=('int16,a6,float32,complex64'))

In [38]:
structured

array([(1, b'first', 0.5, 1.+2.j), (2, b'second', 1.3, 2.-2.j),
       (3, b'third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [40]:
structured[1] #row

(2, b'second', 1.3, 2.-2.j)

In [42]:
structured['f1'] #col

array([b'first', b'second', b'third'], dtype='|S6')

In [45]:
structured = np.array([(1,'first',0.5,1.+2.j),(2,'second',1.3,2.-2.j),(3,'third',0.8,1.+3.j)],dtype=[('id','i2'),('position','S6'),('value','f4'),('complex','c8')])

In [46]:
structured

array([(1, b'first', 0.5, 1.+2.j), (2, b'second', 1.3, 2.-2.j),
       (3, b'third', 0.8, 1.+3.j)],
      dtype=[('id', '<i2'), ('position', 'S6'), ('value', '<f4'), ('complex', '<c8')])

In [47]:
structured.dtype.names=('id','order','value','complex')

In [48]:
structured['order']

array([b'first', b'second', b'third'], dtype='|S6')